Gem::Specification.new do |gem|
  gem.name              = "dummy_performance_tests"
  gem.version           = "0.9.1"
  gem.platform          = Gem::Platform::RUBY
  gem.authors           = ["Gonçalo Silva"]
  gem.email             = ["goncalossilva@gmail.com"]
  gem.homepage          = "http://github.com/goncalossilva/dummy_routes"
  gem.summary           = "Generates dummy performance tests for Rails 3 applications"
  gem.description       = "Generates dummy performance tests for Rails 3 applications by using the data generated by dummy_data and dummy_routes"
  gem.rubyforge_project = gem.name

  gem.required_rubygems_version = ">= 1.3.7"
  
  gem.add_dependency "dummy_data", ">= 0.9"
  gem.add_dependency "dummy_routes", ">= 0.9"
  gem.add_dependency "rails", ">= 3.0.0.beta"

  gem.files        = Dir["{lib}/**/*.rb", "{lib}/**/*.rake", "LICENSE", "*.md"]
  
  gem.require_path = "lib"
end
